root: true
env:
  browser: true
  es2021: true
extends:
  - google
  - plugin:prettier/recommended
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: latest
  sourceType: module
plugins:
  - '@typescript-eslint'
rules: { 'new-cap': 'off', 'valid-jsdoc': 'off', 'require-jsdoc': 'off' }
